Split PR into TF-only and Torch-only variants for GPU (#544)
Signed-off-by: Bharath Ramaswamy <quic_bharathr@quicinc.com>

diff --git a/Jenkins/Jenkinsfile b/Jenkins/Jenkinsfile
--- a/Jenkins/Jenkinsfile
+++ b/Jenkins/Jenkinsfile
@@ -45,8 +45,7 @@ pipeline {
         stage('Pipelines start') {
             parallel {
                 // Start the pipeline for Tensorflow GPU variant
-                //TODO Temporarily running the combined GPU variant instead
-                stage("GPU") {
+                stage("TF GPU") {
                     agent { label "${params.BUILD_LABEL_GPU}" }
                     stages {
                         stage('Setup') {
@@ -54,7 +53,7 @@ pipeline {
                                 cleanWs()
                                 unstash 'AIMETBuildTree'
                                 script{
-                                    env.AIMET_VARIANT_TF_GPU = "tf-torch-gpu"
+                                    env.AIMET_VARIANT_TF_GPU = "tf-gpu"
                                 }
                                 echo "*** Running SETUP stage for ${env.AIMET_VARIANT_TF_GPU} variant on ${env.NODE_NAME} in workspace ${env.WORKSPACE_ROOT} ***"
                             }
@@ -185,121 +184,120 @@ pipeline {
 
 
                 // Start the pipeline for Torch GPU variant
-                //TODO Temporarily skipping this variant
-                // stage("TorchGPU") {
-                //     agent { label "${params.BUILD_LABEL_GPU}" }
-                //     stages {
-                //         stage('Setup') {
-                //             steps {
-                //                 cleanWs()
-                //                 unstash 'AIMETBuildTree'                                
-                //                 script{
-                //                     env.AIMET_VARIANT_TORCH_GPU = "torch-gpu"
-                //                 }
-                //                 echo "*** Running SETUP stage for ${env.AIMET_VARIANT_TORCH_GPU} variant on ${env.NODE_NAME} in workspace ${env.WORKSPACE_ROOT} ***"
-                //             }
-                //         }
+                stage("TorchGPU") {
+                    agent { label "${params.BUILD_LABEL_GPU}" }
+                    stages {
+                        stage('Setup') {
+                            steps {
+                                cleanWs()
+                                unstash 'AIMETBuildTree'
+                                script{
+                                    env.AIMET_VARIANT_TORCH_GPU = "torch-gpu"
+                                }
+                                echo "*** Running SETUP stage for ${env.AIMET_VARIANT_TORCH_GPU} variant on ${env.NODE_NAME} in workspace ${env.WORKSPACE_ROOT} ***"
+                            }
+                        }
 
-                //         stage('Build') {
-                //             steps {
-                //                 echo 'Building code (and generating Docs and pip packages)...'
-                //                 script {
-                //                     //TODO Change option back to "-bp" as soon as issue is fixed
-                //                     runStage(env.AIMET_VARIANT_TORCH_GPU, "-b")
-                //                 }
-                //             }
-                //         }
+                        stage('Build') {
+                            steps {
+                                echo 'Building code (and generating Docs and pip packages)...'
+                                script {
+                                    //TODO Change option back to "-bp" as soon as issue is fixed
+                                    runStage(env.AIMET_VARIANT_TORCH_GPU, "-b")
+                                }
+                            }
+                        }
 
-                //         stage('Code violations') {
-                //             steps {
-                //                 echo 'Running code violations...'
-                //                 script {
-                //                     runStage(env.AIMET_VARIANT_TORCH_GPU, "-v")
-                //                 }
-                //             }
-                //             post {
-                //                 always {
-                //                     step([
-                //                             $class                      : 'WarningsPublisher',
-                //                             parserConfigurations        : [[
-                //                                                             parserName: 'PYLint',
-                //                                                             pattern   : "**/**/**/*pylint_results.out"
-                //                                                           ]],
-                //                             failedTotalHigh             : THRESHOLD_OBJ.pylint_fail_thresholds.high_priority,
-                //                             failedTotalNormal           : THRESHOLD_OBJ.pylint_fail_thresholds.normal_priority,
-                //                             failedTotalLow              : THRESHOLD_OBJ.pylint_fail_thresholds.low_priority,
-                //                             usePreviousBuildAsReference : true
-                //                     ])
-                //                     script {
-                //                         if (currentBuild.currentResult.equals("FAILURE")) {
-                //                             // the plugin won't fail the stage.  it only sets the build status, so we have to fail it
-                //                             // manually
-                //                             sh "exit 1"
-                //                         }
-                //                     }
-                //                 }
-                //             }
-                //         }
+                        stage('Code violations') {
+                            steps {
+                                echo 'Running code violations...'
+                                script {
+                                    runStage(env.AIMET_VARIANT_TORCH_GPU, "-v")
+                                }
+                            }
+                            post {
+                                always {
+                                    step([
+                                            $class                      : 'WarningsPublisher',
+                                            parserConfigurations        : [[
+                                                                            parserName: 'PYLint',
+                                                                            pattern   : "**/**/**/*pylint_results.out"
+                                                                          ]],
+                                            failedTotalHigh             : THRESHOLD_OBJ.pylint_fail_thresholds.high_priority,
+                                            failedTotalNormal           : THRESHOLD_OBJ.pylint_fail_thresholds.normal_priority,
+                                            failedTotalLow              : THRESHOLD_OBJ.pylint_fail_thresholds.low_priority,
+                                            usePreviousBuildAsReference : true
+                                    ])
+                                    script {
+                                        if (currentBuild.currentResult.equals("FAILURE")) {
+                                            // the plugin won't fail the stage.  it only sets the build status, so we have to fail it
+                                            // manually
+                                            sh "exit 1"
+                                        }
+                                    }
+                                }
+                            }
+                        }
 
-                //         stage('Unit tests') {
-                //             steps {
-                //                 script {
-                //                     if ("${env.QCInternalValidation}" == "false") {
-                //                         echo 'Building code and running tests...'
-                //                         runStage(env.AIMET_VARIANT_TORCH_GPU, "-u")
-                //                     }
-                //                 }
-                //             }
-                //             post {
-                //                 always {
-                //                     script {
-                //                         if ("${env.QCInternalValidation}" == "false") {
-                //                             // Parse CTest, Junit, or GoogleTest results
-                //                             step([$class: 'XUnitBuilder', testTimeMargin: '3000', thresholdMode: THRESHOLD_OBJ.unittests_thresholds.threshold_mode,
-                //                                 thresholds: [
-                //                                         [$class: 'FailedThreshold',
-                //                                             failureNewThreshold: THRESHOLD_OBJ.unittests_thresholds.failed_thresholds.new_tests,
-                //                                             failureThreshold: THRESHOLD_OBJ.unittests_thresholds.failed_thresholds.total_tests,
-                //                                             unstableNewThreshold: '',
-                //                                             unstableThreshold: ''],
-                //                                         [$class: 'SkippedThreshold',
-                //                                             failureNewThreshold: THRESHOLD_OBJ.unittests_thresholds.skipped_thresholds.new_tests,
-                //                                             failureThreshold: THRESHOLD_OBJ.unittests_thresholds.skipped_thresholds.total_tests,
-                //                                             unstableNewThreshold: '',
-                //                                             unstableThreshold: '']],
-                //                                 tools: [
-                //                                         [$class: 'CustomType',
-                //                                             customXSL: "${XUNIT_XSL_FILE}",
-                //                                             deleteOutputFiles: false,
-                //                                             failIfNotNew: false,
-                //                                             pattern: "**/unit_test_results/**/*.xml",
-                //                                             skipNoTestFiles: true,
-                //                                             stopProcessingIfError: false]
-                //                                 ]
-                //                             ])
-                //                             if (currentBuild.currentResult.equals("FAILURE")) {
-                //                                 // the plugin won't fail the stage.  it only sets
-                //                                 // the build status, so we have to fail it manually
-                //                                 sh "exit 1"
-                //                             }
-                //                         }
-                //                     }
-                //                 }
-                //             }
-                //         }
+                        stage('Unit tests') {
+                            steps {
+                                script {
+                                    if ("${env.QCInternalValidation}" == "false") {
+                                        echo 'Building code and running tests...'
+                                        runStage(env.AIMET_VARIANT_TORCH_GPU, "-u")
+                                    }
+                                }
+                            }
+                            post {
+                                always {
+                                    script {
+                                        if ("${env.QCInternalValidation}" == "false") {
+                                            // Parse CTest, Junit, or GoogleTest results
+                                            step([$class: 'XUnitBuilder', testTimeMargin: '3000', thresholdMode: THRESHOLD_OBJ.unittests_thresholds.threshold_mode,
+                                                thresholds: [
+                                                        [$class: 'FailedThreshold',
+                                                            failureNewThreshold: THRESHOLD_OBJ.unittests_thresholds.failed_thresholds.new_tests,
+                                                            failureThreshold: THRESHOLD_OBJ.unittests_thresholds.failed_thresholds.total_tests,
+                                                            unstableNewThreshold: '',
+                                                            unstableThreshold: ''],
+                                                        [$class: 'SkippedThreshold',
+                                                            failureNewThreshold: THRESHOLD_OBJ.unittests_thresholds.skipped_thresholds.new_tests,
+                                                            failureThreshold: THRESHOLD_OBJ.unittests_thresholds.skipped_thresholds.total_tests,
+                                                            unstableNewThreshold: '',
+                                                            unstableThreshold: '']],
+                                                tools: [
+                                                        [$class: 'CustomType',
+                                                            customXSL: "${XUNIT_XSL_FILE}",
+                                                            deleteOutputFiles: false,
+                                                            failIfNotNew: false,
+                                                            pattern: "**/unit_test_results/**/*.xml",
+                                                            skipNoTestFiles: true,
+                                                            stopProcessingIfError: false]
+                                                ]
+                                            ])
+                                            if (currentBuild.currentResult.equals("FAILURE")) {
+                                                // the plugin won't fail the stage.  it only sets
+                                                // the build status, so we have to fail it manually
+                                                sh "exit 1"
+                                            }
+                                        }
+                                    }
+                                }
+                            }
+                        }
 
-                //         stage('Static analysis') {
-                //             steps {
-                //                 echo 'Running static analysis...'
-                //                 script {
-                //                     echo 'WARNING: Currently NOT failing on static analysis errors!'
-                //                     //TODO Remove the '| true' from the below invocation when errors are fixed
-                //                     runStage(env.AIMET_VARIANT_TORCH_GPU, "-s | true")
-                //                 }
-                //             }
-                //         }
-                //     }
-                // }
+                        stage('Static analysis') {
+                            steps {
+                                echo 'Running static analysis...'
+                                script {
+                                    echo 'WARNING: Currently NOT failing on static analysis errors!'
+                                    //TODO Remove the '| true' from the below invocation when errors are fixed
+                                    runStage(env.AIMET_VARIANT_TORCH_GPU, "-s | true")
+                                }
+                            }
+                        }
+                    }
+                }
 
 
                 // Start the pipeline for Tensorflow CPU variant
