experimenting with aimet prebuilt image
Signed-off-by: Mohit Prajapati <quic_mprajapa@quicinc.com>

diff --git a/Jenkins/Jenkinsfile b/Jenkins/Jenkinsfile
--- a/Jenkins/Jenkinsfile
+++ b/Jenkins/Jenkinsfile
@@ -5,7 +5,7 @@ pipeline {
         string(name: 'BUILD_LABEL_CPU', defaultValue: 'docker-build-aimet-pr-cpu', description: 'Jenkins node host name or label for CPU variants')
         string(name: 'BUILD_TIMEOUT', defaultValue: '3', description: 'Build timeout in hours')
         string(name: 'USE_LINARO', defaultValue: '-l', description: 'Use pre-built Linaro images, if available.')
-        string(name: 'PREBUILT_DOCKER_IMAGE_URL', defaultValue: '', description: 'Use pre-built docker image from URL, if available.')
+        string(name: 'AIMET_PREBUILT_DOCKER_IMAGE_URL', defaultValue: '', description: 'Use pre-built docker image from URL, if available.')
     }
     agent { label "${params.BUILD_LABEL_CPU}" }
     options {
@@ -45,6 +45,7 @@ pipeline {
             }
         }
 
+<<<<<<< HEAD
         stage("Check Commits") {
             agent { label "${params.BUILD_LABEL_CPU}" }                            
                  
@@ -71,6 +72,116 @@ pipeline {
                     if ("${env.QCInternalValidation}" == "true") {
                         withCredentials([usernameColonPassword(credentialsId: 'neoci-pat', variable: 'USERPASS')]) {
                             sh "AIMET_VARIANT=\"tf-cpu\" bash -l -c \"cd ${REPO_NAME} && ${env.DEPENDENCY_DATA_PATH}/commit_check/commit-checks.sh -e AIMET_VARIANT ${using_linaro} ${env.PREBUILT_DOCKER_IMAGE_URL}\""
+=======
+                        // Run commit checks ONLY in one of the parallel stages
+                        stage('Check commits') {
+                            steps {
+                                echo 'Running commit checks...'
+                                script{
+                                    env.REPO_OR_FORK_URL = "${REPO_URL}"
+                                    using_linaro=env.USE_LINARO
+                                    if (env.CHANGE_FORK != null) {
+                                        env.REPO_OR_FORK_URL = "https://github.com/${env.CHANGE_FORK}/aimet"
+                                    }
+                                    sh "bash -l -c \"git clone ${env.REPO_OR_FORK_URL} -b ${env.CHANGE_BRANCH} commit_checks_repo\""
+                                    if (didDockerFileChange("tf-gpu")) {
+                                            // setting USE LINARO value to EMPTY to rebuild docker image
+                                            using_linaro=""
+                                    }
+                                    if ("${env.QCInternalValidation}" == "true") {
+                                        withCredentials([usernameColonPassword(credentialsId: 'neoci-pat', variable: 'USERPASS')]) {
+                                            sh "AIMET_VARIANT=\"tf-gpu\" AIMET_PREBUILT_DOCKER_IMAGE_URL=\"${params.AIMET_PREBUILT_DOCKER_IMAGE_URL}\" bash -l -c \"cd ${REPO_NAME} && ${env.DEPENDENCY_DATA_PATH}/commit_check/commit-checks.sh -e AIMET_VARIANT ${using_linaro} AIMET_PREBUILT_DOCKER_IMAGE_URL\""
+                                        }
+                                    } else {
+                                        sh "AIMET_VARIANT=\"tf-gpu\" AIMET_PREBUILT_DOCKER_IMAGE_URL=\"${params.AIMET_PREBUILT_DOCKER_IMAGE_URL}\" bash -l -c \"cd ${REPO_NAME} && ${env.DEPENDENCY_DATA_PATH}/commit_check/commit-checks.sh -e AIMET_VARIANT ${using_linaro} AIMET_PREBUILT_DOCKER_IMAGE_URL\""
+                                    }
+                                }
+                                sh "bash -l -c \"rm -rf commit_checks_repo\""
+                            }
+                        }
+
+                        stage('Build') {
+                            steps {
+                                echo 'Building code (and generating Docs and pip packages)...'
+                                script {
+                                    runStage(env.AIMET_VARIANT_TF_GPU, "-bp")
+                                }
+                            }
+                        }
+
+                        stage('Code violations') {
+                            steps {
+                                echo 'Running code violations...'
+                                script {
+                                    runStage(env.AIMET_VARIANT_TF_GPU, "-v")
+                                }
+                            }
+                            // post {
+                            //     always {
+                            //         step([
+                            //                 $class                      : 'WarningsPublisher',
+                            //                 parserConfigurations        : [[
+                            //                                                 parserName: 'PYLint',
+                            //                                                 pattern   : "**/**/**/*pylint_results.out"
+                            //                                               ]],
+                            //                 failedTotalHigh             : THRESHOLD_OBJ.pylint_fail_thresholds.high_priority,
+                            //                 failedTotalNormal           : THRESHOLD_OBJ.pylint_fail_thresholds.normal_priority,
+                            //                 failedTotalLow              : THRESHOLD_OBJ.pylint_fail_thresholds.low_priority,
+                            //                 usePreviousBuildAsReference : true
+                            //         ])
+                            //         script {
+                            //             if (currentBuild.currentResult.equals("FAILURE")) {
+                            //                 // the plugin won't fail the stage.  it only sets the build status, so we have to fail it
+                            //                 // manually
+                            //                 sh "exit 1"
+                            //             }
+                            //         }
+                            //     }
+                            // }
+                        }
+
+                        stage('Unit tests') {
+                            steps {
+                                script {
+                                    if ("${env.QCInternalValidation}" == "false") {
+                                        echo 'Building code and running tests...'
+                                        runStage(env.AIMET_VARIANT_TF_GPU, "-u")
+                                    }
+                                }
+                            }
+                            post {
+                                always {
+                                    script {
+                                        if ("${env.QCInternalValidation}" == "false") {
+                                            // Parse CTest, Junit, or GoogleTest results
+                                            xunit thresholdMode: 2,
+                                            thresholds: [
+                                                failed(failureNewThreshold: THRESHOLD_OBJ.unittests_thresholds.failed_thresholds.new_tests,
+                                                    failureThreshold: THRESHOLD_OBJ.unittests_thresholds.failed_thresholds.total_tests,
+                                                    unstableNewThreshold: THRESHOLD_OBJ.unittests_thresholds.skipped_thresholds.new_tests,
+                                                    unstableThreshold: THRESHOLD_OBJ.unittests_thresholds.skipped_thresholds.total_tests)],
+                                            tools: [Custom(customXSL: "${XUNIT_XSL_FILE}",
+                                                        deleteOutputFiles: false,
+                                                        excludesPattern: '',
+                                                        pattern: "**/unit_test_results/**/*.xml",
+                                                        skipNoTestFiles: true,
+                                                        stopProcessingIfError: true)]
+                                        }
+                                    }
+                                }
+                            }
+                        }
+
+                        stage('Static analysis') {
+                            steps {
+                                echo 'Running static analysis...'
+                                script {
+                                    echo 'WARNING: Currently NOT failing on static analysis errors!'
+                                    //TODO Remove the '| true' from the below invocation when errors are fixed
+                                    runStage(env.AIMET_VARIANT_TF_GPU, "-s | true")
+                                }
+                            }
+>>>>>>> a4938b66 (experimenting with aimet prebuilt image)
                         }
                     } else {
                         sh "AIMET_VARIANT=\"tf-cpu\" bash -l -c \"cd ${REPO_NAME} && ${env.DEPENDENCY_DATA_PATH}/commit_check/commit-checks.sh -e AIMET_VARIANT ${using_linaro} ${env.PREBUILT_DOCKER_IMAGE_URL}\""
@@ -281,8 +392,8 @@ pipeline {
                                 steps {
                                     echo "*** Running Docker stage for ${AIMET_VARIANT} variant on ${env.NODE_NAME} in workspace ${env.WORKSPACE_ROOT} ***"
                                     script {
-                                        if (env.AIMET_PREBUILT_DOCKER_IMAGE_URL && ! pullRequest.files.any { f -> f.getFilename().contains('Dockerfile') }) {
-                                            DOCKER_IMAGE_FULL_URL = "${env.AIMET_PREBUILT_DOCKER_IMAGE_URL}/${env.DOCKER_IMAGE}"
+                                        if (params.AIMET_PREBUILT_DOCKER_IMAGE_URL && ! pullRequest.files.any { f -> f.getFilename().contains('Dockerfile') }) {
+                                            DOCKER_IMAGE_FULL_URL = "${params.AIMET_PREBUILT_DOCKER_IMAGE_URL}/${env.DOCKER_IMAGE}"
                                             sh "docker pull ${DOCKER_IMAGE_FULL_URL} && docker tag ${DOCKER_IMAGE_FULL_URL} ${env.DOCKER_IMAGE}"
                                         } else {
                                             env.DOCKER_IMAGE = "${env.DOCKER_IMAGE}.${CHANGE_ID}"
@@ -404,7 +515,7 @@ def runStage(aimet_variant, options) {
             using_linaro=""
         }
         sh """
-            AIMET_VARIANT=${aimet_variant} bash -l -c "cd ${REPO_NAME} && ./buildntest.sh -e AIMET_VARIANT ${options} ${using_linaro} ${env.PREBUILT_DOCKER_IMAGE_URL}"
+            AIMET_VARIANT=${aimet_variant} bash -l -c "cd ${REPO_NAME} && ./buildntest.sh -e AIMET_VARIANT ${options} ${using_linaro} ${params.AIMET_PREBUILT_DOCKER_IMAGE_URL}"
         """
     }
 }
